# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o ticket.o cashbox.o Filqht.o
LINKOBJ  = main.o ticket.o cashbox.o Filqht.o
LIBS     = -L"C:/Users/bodia/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Users/bodia/Dev-Cpp/MinGW64/include" -I"C:/Users/bodia/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/bodia/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/bodia/Dev-Cpp/MinGW64/include" -I"C:/Users/bodia/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/bodia/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/bodia/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

ticket.o: ticket.cpp
	$(CPP) -c ticket.cpp -o ticket.o $(CXXFLAGS)

cashbox.o: cashbox.cpp
	$(CPP) -c cashbox.cpp -o cashbox.o $(CXXFLAGS)

Filqht.o: Filqht.cpp
	$(CPP) -c Filqht.cpp -o Filqht.o $(CXXFLAGS)
